In [6]:
import json
import pandas as pd
import numpy as np
import datetime
import time
from tqdm import tqdm, tqdm_notebook

In [7]:
# 字典轉list
def user_dict_list():
    user_dict_list=[]
    with open('data/jieba_data/user_receipt.txt','r',encoding='utf-8') as f:
        for line in f:
            user_dict_list.append(line.strip('\n'))
    return user_dict_list
print(user_dict_list())

['微波麵', '泡麵', '台酒TTL', '味味一品', '味王', '阿舍', '隨緣', '素飄香', '日清', '農心', '不倒翁', '百勝廚', '維力', '滿漢大餐', '拉麵道', '味味A', '阿Q', '統一麵', 'MAMA', '桂冠', '科學麵', '手打', '一度', '(速食麵)', '(泡麵)', '速食麵', '泡麵', '罐頭', '八寶', '十穀', '薏仁', '花生', '綠豆', '玉米', '燕麥', '(泰山)', '泰山', '牛頭牌', '愛之味', '土豆麵筋', '鮮味脆瓜', '青脆菜心', '壺底蔭瓜', '鮮脆條瓜', '甜辣醬', '珍保玉筍', '韓式泡菜', '珍寶', '鮪魚', '玉米', '大茂', '麵筋', '三寶', '大土豆', '幼條瓜', '蔭瓜', '黑瓜', '菜心', '幼筍', '台鳳', '水蜜桃', '水果', '玉米', '鳳梨', '花生', '麵筋', '脆瓜', '菜心', '玉筍', '瓜仔肉', '剝皮辣椒', '永偉', '綠巨人', '衛生紙', '面紙']

In [8]:
# 讀大檔案前幾筆 nrows
df = pd.read_csv('data/invoice_qmonster.csv',header=None,encoding='utf8', nrows=2)
df.columns=['inv_id','item_no','product_name','unit_price','quantity','amonut','inv_time','login_time','company_name','seller_address','unknow','gender','age']
df

,inv_id,item_no,product_name,unit_price,quantity,amonut,inv_time,login_time,company_name,seller_address,unknow,gender,age
0,62640150,1,美滿補精,600.0,4,2400.0,2019-12-31 09:35:25.000000,2020-01-01 02:14:04.000000,善種子事業有限公司,高雄市800高雄市新興區五福二路116號4樓,074fec1be438749582cb4e832e4c6a0c86b8a29c,1,30
1,62640150,2,美滿補精,0.0,2,0.0,2019-12-31 09:35:25.000000,2020-01-01 02:14:04.000000,善種子事業有限公司,高雄市800高雄市新興區五福二路116號4樓,074fec1be438749582cb4e832e4c6a0c86b8a29c,1,30

In [14]:
# 讀取7G多檔案大小。更改運算邏輯 (iterrows 改 str.contains) 從8小時降為3分鐘

# 因df資料較大，使用chunk進行區塊處理，中間將不包含指定list內容去掉
tStart = time.time()
df = pd.read_csv('data/invoice_qmonster.csv',header=None,encoding='utf8', chunksize=10000)
for chunk in df:
    chunk.columns=['inv_id','item_no','product_name','unit_price','quantity','amonut','inv_time','login_time','company_name','seller_address','unknow','gender','age']
    chunk = chunk[chunk['product_name'].str.contains('|'.join(user_dict_list()), na=False)]  # na : default NaN, fill value for missing values.
    chunk.to_csv('testtest.csv', mode='a',index=0, header=0,encoding='utf-8-sig')
    print(chunk['inv_time'])
tEnd = time.time()
print('花費時間',tEnd-tStart)

    2020-08-09 00:48:59.000000
27819979    2020-08-09 00:50:19.000000
27819988    2020-08-09 00:50:19.000000
Name: inv_time, Length: 433, dtype: object
27820040    2020-08-09 01:04:35.000000
27820177    2020-08-09 01:25:14.000000
27820180    2020-08-09 01:25:14.000000
27820217    2020-08-09 01:26:50.000000
27820218    2020-08-09 01:26:50.000000
                       ...
27829826    2020-08-09 12:02:54.000000
27829871    2020-08-09 12:03:32.000000
27829879    2020-08-09 12:03:39.000000
27829885    2020-08-09 12:03:39.000000
27829967    2020-08-09 12:12:04.000000
Name: inv_time, Length: 370, dtype: object
27830042    2020-08-09 12:13:54.000000
27830272    2020-08-09 12:20:41.000000
27830316    2020-08-09 12:23:19.000000
27830319    2020-08-09 12:23:19.000000
27830353    2020-08-09 12:24:45.000000
                       ...
27839920    2020-08-09 15:38:55.000000
27839927    2020-08-09 15:38:55.000000
27839946    2020-08-09 15:39:00.000000
27839954    2020-08-09 15:39:00.000000
27839979    2020-08-09 15:39:08.000000
Name: inv_time, Length: 473, dtype: object
27840000    2020-08-09 15:39:13.000000
27840025    2020-08-09 15:39:16.000000
27840061    2020-08-09 15:39:44.000000
27840089    2020-08-09 15:40:32.000000
27840115    2020-08-09 15:40:50.000000
                       ...
27849686    2020-08-09 17:35:52.000000
27849709    2020-08-09 17:36:04.000000
27849710    2020-08-09 17:36:04.000000
27849712    2020-08-09 17:36:04.000000
27849768    2020-08-09 17:36:27.000000
Name: inv_time, Length: 424, dtype: object
27850001    2020-08-09 17:37:48.000000
27850004    2020-08-09 17:37:48.000000
27850005    2020-08-09 17:37:48.000000
27850009    2020-08-09 17:37:48.000000
27850089    2020-08-09 17:38:21.000000
                       ...
27859882    2020-08-09 19:33:38.000000
27859963    2020-08-09 19:34:22.000000
27859967    2020-08-09 19:34:22.000000
27859968    2020-08-09 19:34:22.000000
27859969    2020-08-09 19:34:22.000000
Name: inv_time, Length: 487, dtype: object
27860059    2020-08-09 19:34:55.000000
27860060    2020-08-09 19:34:55.000000
27860070    2020-08-09 19:34:57.000000
27860093    2020-08-09 19:35:09.000000
27860094    2020-08-09 19:35:11.000000
                       ...
27869877    2020-08-09 21:16:25.000000
27869878    2020-08-09 21:16:25.000000
27869879    2020-08-09 21:16:25.000000
27869935    2020-08-09 21:16:50.000000
27869991    2020-08-09 21:17:08.000000
Name: inv_time, Length: 412, dtype: object
27870000    2020-08-09 21:17:10.000000
27870002    2020-08-09 21:17:10.000000
27870004    2020-08-09 21:17:10.000000
27870023    2020-08-09 21:17:17.000000
27870046    2020-08-09 21:17:24.000000
                       ...
27879878    2020-08-09 23:15:48.000000
27879917    2020-08-09 23:16:11.000000
27879955    2020-08-09 23:16:27.000000
27879965    2020-08-09 23:16:32.000000
27879973    2020-08-09 23:16:34.000000
Name: inv_time, Length: 376, dtype: object
27880023    2020-08-09 23:17:04.000000
27880071    2020-08-09 23:17:42.000000
27880072    2020-08-09 23:17:42.000000
27880085    2020-08-09 23:17:50.000000
27880163    2020-08-09 23:18:50.000000
                       ...
27889963    2020-08-10 07:32:25.000000
27889964    2020-08-10 07:32:25.000000
27889976    2020-08-10 07:34:55.000000
27889977    2020-08-10 07:34:55.000000
27889997    2020-08-10 07:35:14.000000
Name: inv_time, Length: 386, dtype: object
27890025    2020-08-10 07:37:51.000000
27890029    2020-08-10 07:38:25.000000
27890030    2020-08-10 07:38:25.000000
27890063    2020-08-10 07:43:34.000000
27890070    2020-08-10 07:43:47.000000
                       ...
27899963    2020-08-10 14:39:49.000000
27899964    2020-08-10 14:39:49.000000
27899965    2020-08-10 14:39:49.000000
27899967    2020-08-10 14:39:49.000000
27899980    2020-08-10 14:40:06.000000
Name: inv_time, Length: 416, dtype: object
27900028    2020-08-10 14:40:42.000000
27900048    2020-08-10 14:41:19.000000
27900050    2020-08-10 14:41:21.000000
27900083    2020-08-10 14:41:43.000000
27900107    2020-08-10 14:42:10.000000
                       ...
27909817    2020-08-10 18:54:56.000000
27909819    2020-08-10 18:54:56.000000
27909882    2020-08-10 18:55:44.000000
27909941    2020-08-10 18:56:13.000000
27909957    2020-08-10 18:56:20.000000
Name: inv_time, Length: 481, dtype: object
27910019    2020-08-10 18:57:17.000000
27910039    2020-08-10 18:57:45.000000
27910061    2020-08-10 18:58:04.000000
27910065    2020-08-10 18:58:04.000000
27910066    2020-08-10 18:58:04.000000
                       ...
27919903    2020-08-10 21:36:36.000000
27919923    2020-08-10 21:36:45.000000
27919928    2020-08-10 21:36:50.000000
27919929    2020-08-10 21:36:53.000000
27919957    2020-08-10 21:37:06.000000
Name: inv_time, Length: 433, dtype: object
27920141    2020-08-10 21:41:41.000000
27920204    2020-08-10 21:42:42.000000
27920210    2020-08-10 21:42:54.000000
27920234    2020-08-10 21:43:45.000000
27920235    2020-08-10 21:43:45.000000
                       ...
27929782    2020-08-11 00:56:12.000000
27929882    2020-06-07 12:03:40.000000
27929956    2020-08-11 01:16:52.000000
27929961    2020-08-11 01:17:36.000000
27929971    2020-08-11 01:21:06.000000
Name: inv_time, Length: 392, dtype: object
27930013    2020-08-11 01:24:23.000000
27930014    2020-08-11 01:24:23.000000
27930137    2020-08-11 01:32:25.000000
27930156    2020-08-11 01:33:19.000000
27930177    2020-08-11 01:35:24.000000
                       ...
27939925    2020-08-11 14:53:25.000000
27939938    2020-08-11 14:53:33.000000
27939941    2020-08-11 14:53:37.000000
27939950    2020-08-11 14:53:48.000000
27939957    2020-08-11 14:53:52.000000
Name: inv_time, Length: 413, dtype: object
27940002    2020-08-11 14:54:58.000000
27940088    2020-08-11 14:57:56.000000
27940108    2020-08-11 14:58:47.000000
27940116    2020-08-11 14:59:00.000000
27940117    2020-08-11 14:59:00.000000
                       ...
27949947    2020-08-11 18:51:31.000000
27949969    2020-08-11 18:51:56.000000
27949971    2020-08-11 18:51:58.000000
27949980    2020-08-11 18:52:00.000000
27949981    2020-08-11 18:52:00.000000
Name: inv_time, Length: 436, dtype: object
27950040    2020-08-11 18:53:00.000000
27950055    2020-08-11 18:53:19.000000
27950078    2020-08-11 18:53:35.000000
27950105    2020-08-11 18:54:04.000000
27950124    2020-04-18 07:09:57.000000
                       ...
27959830    2020-08-11 21:23:33.000000
27959853    2020-08-11 21:23:45.000000
27959882    2020-08-11 21:24:01.000000
27959921    2020-08-11 21:24:19.000000
27959967    2020-08-11 21:24:53.000000
Name: inv_time, Length: 447, dtype: object
27960054    2020-08-11 21:25:40.000000
27960115    2020-08-11 21:26:06.000000
27960117    2020-08-11 21:26:09.000000
27960122    2020-08-11 21:26:13.000000
27960160    2020-08-11 21:27:07.000000
                       ...
27969858    2020-08-12 00:03:55.000000
27969864    2020-08-12 00:04:07.000000
27969907    2020-08-12 00:05:31.000000
27969910    2020-08-12 00:05:34.000000
27969922    2020-08-12 00:05:50.000000
Name: inv_time, Length: 475, dtype: object
27970050    2020-08-12 00:08:01.000000
27970093    2020-08-12 00:09:30.000000
27970099    2020-08-12 00:09:40.000000
27970117    2020-08-12 00:10:01.000000
27970121    2020-08-12 00:10:11.000000
                       ...
27979874    2020-08-12 11:59:15.000000
27979892    2020-08-12 11:59:27.000000
27979914    2020-08-12 11:59:40.000000
27979967    2020-08-12 12:00:40.000000
27979978    2020-08-12 12:00:54.000000
Name: inv_time, Length: 456, dtype: object
27980013    2020-08-12 12:02:18.000000
27980018    2020-08-12 12:02:18.000000
27980020    2020-08-12 12:02:18.000000
27980033    2020-08-12 12:02:26.000000
27980055    2020-08-12 12:03:38.000000
                       ...
27989884    2020-08-12 17:36:05.000000
27989897    2020-08-12 17:36:17.000000
27989937    2020-08-12 17:37:05.000000
27989960    2020-08-12 17:37:34.000000
27989987    2020-08-12 17:38:06.000000
Name: inv_time, Length: 467, dtype: object
27990019    2020-08-12 17:38:57.000000
27990020    2020-08-12 17:38:57.000000
27990023    2020-08-12 17:38:59.000000
27990051    2020-08-12 17:39:41.000000
27990076    2020-08-12 17:39:54.000000
                       ...
27999917    2020-08-12 22:23:27.000000
27999950    2020-08-12 22:24:14.000000
27999956    2020-08-12 22:24:16.000000
27999963    2020-08-12 22:24:22.000000
27999975    2020-08-12 22:24:31.000000
Name: inv_time, Length: 485, dtype: object
28000033    2020-08-12 22:25:20.000000
28000044    2020-08-12 22:25:27.000000
28000048    2020-08-12 22:25:37.000000
28000050    2020-08-12 22:25:37.000000
28000051    2020-08-12 22:25:37.000000
                       ...
28009894    2020-08-13 02:37:01.000000
28009903    2020-08-13 02:37:06.000000
28009946    2020-08-13 02:40:53.000000
28009987    2020-08-13 02:42:46.000000
28009988    2020-08-13 02:42:46.000000
Name: inv_time, Length: 419, dtype: object
28010004    2020-08-13 02:43:43.000000
28010046    2020-08-13 02:48:45.000000
28010053    2020-08-13 02:52:22.000000
28010074    2020-08-13 02:53:17.000000
28010110    2020-08-13 02:54:47.000000
                       ...
28019850    2020-08-13 13:55:17.000000
28019872    2020-08-13 13:55:36.000000
28019879    2020-08-13 13:55:40.000000
28019937    2020-08-13 13:56:15.000000
28019948    2020-08-13 13:56:22.000000
Name: inv_time, Length: 443, dtype: object
28020025    2020-08-13 13:57:00.000000
28020085    2020-08-13 13:57:21.000000
28020092    2020-08-13 13:57:26.000000
28020104    2020-08-13 13:57:42.000000
28020116    2020-08-13 13:57:47.000000
                       ...
28029823    2020-08-13 19:08:30.000000
28029931    2020-08-13 19:11:18.000000
28029960    2020-08-13 19:11:49.000000
28029961    2020-08-13 19:11:49.000000
28029962    2020-08-13 19:11:49.000000
Name: inv_time, Length: 476, dtype: object
28030014    2020-08-13 19:14:41.000000
28030026    2020-08-13 19:16:07.000000
28030144    2020-08-13 19:16:55.000000
28030215    2020-08-13 19:17:28.000000
28030218    2020-08-13 19:17:28.000000
                       ...
28039892    2020-08-13 22:22:50.000000
28039898    2020-08-13 22:22:55.000000
28039901    2020-08-13 22:22:57.000000
28039948    2020-08-13 22:23:28.000000
28039978    2020-08-13 22:24:12.000000
Name: inv_time, Length: 461, dtype: object
28040015    2020-08-13 22:24:33.000000
28040022    2020-08-13 22:24:38.000000
28040029    2020-08-13 22:24:42.000000
28040085    2020-08-13 22:24:59.000000
28040112    2020-08-13 22:25:40.000000
                       ...
28049850    2020-08-14 10:26:42.000000
28049860    2020-08-14 10:26:52.000000
28049901    2020-08-14 10:27:55.000000
28049922    2020-08-14 10:29:49.000000
28049931    2020-08-14 10:29:58.000000
Name: inv_time, Length: 454, dtype: object
28050028    2020-08-14 10:31:36.000000
28050029    2020-08-14 10:31:36.000000
28050038    2020-08-14 10:31:46.000000
28050039    2020-08-14 10:31:46.000000
28050046    2020-08-14 10:32:01.000000
                       ...
28059951    2020-08-14 16:33:22.000000
28059952    2020-08-14 16:33:22.000000
28059966    2020-08-14 16:33:35.000000
28059982    2020-08-14 16:33:56.000000
28059997    2020-08-14 16:34:13.000000
Name: inv_time, Length: 467, dtype: object
28060042    2020-06-22 12:22:31.000000
28060078    2020-08-14 16:41:10.000000
28060091    2020-08-14 16:41:13.000000
28060109    2020-08-14 16:42:03.000000
28060110    2020-08-14 16:42:07.000000
                       ...
28069905    2020-08-14 21:42:08.000000
28069972    2020-08-14 21:43:53.000000
28069973    2020-08-14 21:43:53.000000
28069995    2020-08-14 21:44:08.000000
28069996    2020-08-14 21:44:08.000000
Name: inv_time, Length: 420, dtype: object
28070016    2020-08-14 21:44:31.000000
28070053    2020-08-14 21:45:28.000000
28070061    2020-08-14 21:45:37.000000
28070062    2020-08-14 21:45:37.000000
28070073    2020-08-14 21:46:04.000000
                       ...
28079748    2020-08-15 09:53:02.000000
28079749    2020-08-15 09:53:02.000000
28079926    2020-08-15 09:55:35.000000
28079935    2020-08-15 09:55:39.000000
28079949    2020-08-15 09:56:03.000000
Name: inv_time, Length: 439, dtype: object
28080038    2020-08-15 09:58:36.000000
28080061    2020-08-15 09:59:25.000000
28080217    2020-08-15 10:02:47.000000
28080218    2020-08-15 10:02:47.000000
28080252    2020-08-15 10:03:31.000000
                       ...
28089858    2020-08-15 15:33:28.000000
28089859    2020-08-15 15:33:28.000000
28089882    2020-08-15 15:35:23.000000
28089889    2020-08-15 15:36:26.000000
28089980    2020-08-15 15:38:08.000000
Name: inv_time, Length: 388, dtype: object
28090003    2020-08-15 15:38:53.000000
28090027    2020-08-15 15:39:57.000000
28090028    2020-08-15 15:39:59.000000
28090045    2020-08-15 15:40:25.000000
28090075    2020-08-15 15:41:05.000000
                       ...
28099951    2020-08-15 20:54:50.000000
28099954    2020-08-15 20:54:55.000000
28099973    2020-08-15 20:55:28.000000
28099974    2020-08-15 20:55:28.000000
28099977    2020-08-15 20:55:31.000000
Name: inv_time, Length: 418, dtype: object
28100010    2020-08-15 20:55:50.000000
28100018    2020-08-15 20:55:59.000000
28100033    2020-08-15 20:56:33.000000
28100048    2020-08-15 20:57:05.000000
28100051    2020-08-15 20:57:09.000000
                       ...
28109793    2020-08-16 09:56:02.000000
28109847    2020-08-16 09:56:32.000000
28109909    2020-08-16 09:57:07.000000
28109931    2020-08-16 09:57:21.000000
28109998    2020-08-16 09:57:55.000000
Name: inv_time, Length: 419, dtype: object
28110053    2020-08-16 09:58:06.000000
28110056    2020-08-16 09:58:08.000000
28110068    2020-08-16 09:58:08.000000
28110103    2020-08-16 09:58:31.000000
28110109    2020-08-16 09:58:42.000000
                       ...
28119964    2020-08-16 16:00:44.000000
28119969    2020-08-16 16:00:48.000000
28119978    2020-08-16 16:01:28.000000
28119982    2020-08-16 16:01:35.000000
28119986    2020-08-16 16:01:35.000000
Name: inv_time, Length: 437, dtype: object
28120007    2020-05-05 19:36:40.000000
28120011    2020-05-05 19:36:40.000000
28120016    2020-05-05 19:36:40.000000
28120019    2020-05-05 19:36:40.000000
28120035    2020-05-05 19:36:40.000000
                       ...
28129871    2020-08-16 19:45:10.000000
28129976    2020-08-16 19:46:49.000000
28129983    2020-08-16 19:46:51.000000
28129984    2020-08-16 19:46:51.000000
28129999    2020-08-16 19:46:58.000000
Name: inv_time, Length: 493, dtype: object
28130027    2020-08-16 19:47:21.000000
28130030    2020-08-16 19:47:21.000000
28130033    2020-08-16 19:47:21.000000
28130038    2020-08-16 19:47:21.000000
28130054    2020-08-16 19:47:48.000000
                       ...
28139806    2020-08-16 22:40:03.000000
28139825    2020-08-16 22:40:10.000000
28139829    2020-08-16 22:40:10.000000
28139830    2020-08-16 22:40:10.000000
28139866    2020-08-16 22:40:23.000000
Name: inv_time, Length: 417, dtype: object
28140076    2020-08-16 22:43:14.000000
28140077    2020-08-16 22:43:14.000000
28140078    2020-08-16 22:43:14.000000
28140080    2020-08-16 22:43:14.000000
28140081    2020-08-16 22:43:14.000000
                       ...
28149922    2020-08-17 12:08:53.000000
28149937    2020-08-17 12:08:59.000000
28149946    2020-08-17 12:09:03.000000
28149958    2020-08-17 12:09:09.000000
28149961    2020-08-17 12:09:11.000000
Name: inv_time, Length: 455, dtype: object
28150025    2020-08-17 12:09:50.000000
28150030    2020-08-17 12:09:52.000000
28150051    2020-08-17 12:10:09.000000
28150068    2020-08-17 12:10:22.000000
28150096    2020-08-17 12:10:56.000000
                       ...
28159912    2020-08-17 18:25:42.000000
28159926    2020-08-17 18:25:51.000000
28159953    2020-08-17 18:26:41.000000
28159963    2020-08-17 18:27:25.000000
28159995    2020-08-17 18:28:08.000000
Name: inv_time, Length: 466, dtype: object
28160004    2020-08-17 18:28:08.000000
28160008    2020-08-17 18:28:08.000000
28160039    2020-08-17 18:28:46.000000
28160041    2020-08-17 18:28:47.000000
28160051    2020-08-17 18:28:54.000000
                       ...
28169827    2020-08-17 21:57:35.000000
28169859    2020-08-17 21:58:49.000000
28169893    2020-08-17 21:59:30.000000
28169907    2020-08-17 22:00:06.000000
28169972    2020-08-17 22:00:20.000000
Name: inv_time, Length: 444, dtype: object
28170251    2020-08-17 22:01:12.000000
28170292    2020-08-17 22:02:36.000000
28170295    2020-08-17 22:02:42.000000
28170370    2020-08-17 22:03:58.000000
28170404    2020-08-17 22:04:21.000000
                       ...
28179866    2020-08-18 10:27:21.000000
28179870    2020-08-18 10:27:31.000000
28179910    2020-08-18 10:28:55.000000
28179930    2020-08-18 10:29:26.000000
28179982    2020-08-18 10:31:06.000000
Name: inv_time, Length: 404, dtype: object
28180021    2020-08-18 10:33:49.000000
28180031    2020-08-18 10:35:41.000000
28180054    2020-08-18 10:38:14.000000
28180056    2020-08-18 10:38:38.000000
28180062    2020-08-18 10:40:03.000000
                       ...
28189832    2020-08-18 19:11:09.000000
28189837    2020-08-18 19:11:23.000000
28189838    2020-08-18 19:11:23.000000
28189890    2020-08-18 19:13:14.000000
28189908    2020-08-18 19:13:40.000000
Name: inv_time, Length: 490, dtype: object
28190040    2020-08-18 19:17:50.000000
28190064    2020-08-18 19:18:22.000000
28190162    2020-08-18 19:20:52.000000
28190178    2020-06-17 18:47:47.000000
28190179    2020-06-17 18:47:47.000000
                       ...
28199860    2020-08-18 23:38:57.000000
28199880    2020-08-18 23:39:04.000000
28199888    2020-08-18 23:39:11.000000
28199889    2020-08-18 23:39:11.000000
28199984    2020-08-18 23:40:24.000000
Name: inv_time, Length: 344, dtype: object
28200020    2020-08-18 23:40:36.000000
28200049    2020-08-18 23:41:02.000000
28200072    2020-08-18 23:41:18.000000
28200079    2020-08-18 23:41:30.000000
28200158    2020-08-18 23:43:06.000000
                       ...
28209776    2020-08-19 12:02:11.000000
28209851    2020-08-19 12:03:27.000000
28209912    2020-08-19 12:06:32.000000
28209927    2020-08-19 12:07:04.000000
28209958    2020-08-19 12:07:36.000000
Name: inv_time, Length: 463, dtype: object
28210097    2020-08-19 12:17:37.000000
28210177    2020-08-19 12:23:05.000000
28210182    2020-08-19 12:23:22.000000
28210185    2020-08-19 12:23:31.000000
28210189    2020-08-19 12:23:43.000000
                       ...
28219925    2020-08-19 19:48:27.000000
28219942    2020-08-19 19:48:57.000000
28219966    2020-08-19 19:49:36.000000
28219977    2020-08-19 19:49:53.000000
28219994    2020-08-19 19:50:33.000000
Name: inv_time, Length: 429, dtype: object
28220026    2020-08-19 19:51:01.000000
28220032    2020-08-19 19:51:24.000000
28220072    2020-08-19 19:51:49.000000
28220082    2020-08-19 19:52:31.000000
28220091    2020-08-19 19:52:31.000000
                       ...
28229977    2020-08-20 00:33:39.000000
28229981    2020-08-20 00:33:47.000000
28229982    2020-08-20 00:33:47.000000
28229983    2020-08-20 00:33:47.000000
28229993    2020-08-20 00:34:01.000000
Name: inv_time, Length: 429, dtype: object
28230011    2020-08-20 00:34:44.000000
28230041    2020-08-20 00:36:07.000000
28230061    2020-08-20 00:36:33.000000
28230096    2020-08-20 00:37:34.000000
28230103    2020-08-20 00:37:44.000000
                       ...
28234970    2020-08-20 09:56:24.000000
28234981    2020-08-20 09:56:59.000000
28235022    2020-08-20 09:57:39.000000
28235092    2020-08-20 09:59:09.000000
28235110    2020-08-20 09:59:22.000000
Name: inv_time, Length: 233, dtype: object
花費時間 184.85406184196472

In [16]:
df = pd.read_csv('data/invoice_qmonster.csv',header=None,encoding='utf8')
len(df)

28235132